id: P4A08ACAF
initial_creation_type: input
source_metadata:
  Title: Dhāraṇī Saṃgraha
  Editor: Atul Bhosekar
  Publisher: '-'
  Place of Publication: '-'
  Year: '2017'
  Dhāraṇī Saṃgraha:
    Text Version: Romanized
    Input Personnel: Miroj Shakya & Milan Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:16:22.451897'
last_modified_at: '2022-03-08T17:16:22.451907'
